server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: user-service
#  cloud:
#    nacos:
#      server-addr: 192.168.1.106:8848 #nacos 地址
#      discovery:
#        cluster-name: SH #集群名称

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl