server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 192.168.1.106:8848  #nacos 地址
    sentinel:
      transport:
        dashboard: localhost:8080
#      discovery:
#        cluster-name: HZ #集群名称
#        namespace: 1ce95f0a-1a39-4a04-8ab2-92b15c6c3161 # 配置namespace
#        ephemeral: false  #是否是临时实列 ，默认是临时
#不同命名空间的服务是不可见的
#同一命名空间，不同集群的服务是可见的
#可以针对某个服务配置负载均衡策略
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  #配置负载均衡的规则，优先选贼本地集群

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#  type-aliases-package: com.example.userservice.entity

#feign 的优化，可以配置httpClient或okClient
feign:
  httpclient:
    enabled: true #支持httpclient的开关
    max-connections-per-route: 50 #单个路径下的最大连接数
    max-connections: 200 #最大连接数
  sentinel:
    enabled: true  #开启feign对sentinel的支持
#ribbon:
#  eager-load:
#    enabled: true  #ribbon默认是懒加载，可以通过配置开启饥饿加载
#    clients: user-service  #指定饥饿加载的服务名称，可以是多个
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: ""
      group: DEFAULT_GROUP
      application: seata-tc-server
      username: nacos
      password: nacos
  tx-service-group: seata-demo
  service:
    vgroup-mapping:
      seata-demo: HZ
